-- 코드를 작성해주세요
SELECT
    ROUTE
    , CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE
    , CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM
    SUBWAY_DISTANCE
GROUP BY
    ROUTE
# concat 사용 시 order by 적용 X
ORDER BY
    ROUND(SUM(D_BETWEEN_DIST), 1) DESC;