-- 코드를 작성해주세요
SELECT
    COUNT(FISH.ID) AS FISH_COUNT
FROM
    FISH_INFO FISH
LEFT OUTER JOIN
    FISH_NAME_INFO NAME
ON
    FISH.FISH_TYPE = NAME.FISH_TYPE
WHERE
    NAME.FISH_NAME IN ('BASS', 'SNAPPER');