-- 코드를 입력하세요
SELECT
    BOARD.TITLE
    , BOARD.BOARD_ID
    , REPLY.REPLY_ID
    , REPLY.WRITER_ID
    , REPLY.CONTENTS
    , DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM
    USED_GOODS_BOARD BOARD
JOIN
    USED_GOODS_REPLY REPLY
ON
    BOARD.BOARD_ID = REPLY.BOARD_ID
# select 절 보다 where 절이 먼저 읽힘 -> 별칭 사용 불가
# like 보다는 =가 성능측면에서 good
WHERE
     BOARD.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY
    CREATED_DATE ASC
    , BOARD.TITLE ASC;